<?php

function day24Prog( array $lines ) : string {
    $fun = 'function day24dyn($d0, $d1, $d2, $d3, $d4, $d5, $d6, $d7, $d8, $d9, $d10, $d11, $d12, $d13) {' . PHP_EOL;
    $fun .= '$x = 0;' . PHP_EOL . '$y = 0;' . PHP_EOL . '$z = 0;' . PHP_EOL;
    $d = 0;
    foreach ($lines as $line) {
        if ( strlen($line ) > 0 ) {
            $toks = explode(' ', $line);
            if ( $toks[0] === 'inp') {
                $fun .= '$' . $toks[1] . ' = $d' . $d . ';' . PHP_EOL;
                $d++;
            } else {
                $tok2 = is_numeric( $toks[2] ) ? $toks[2] : '$' . $toks[2];
                if ( $toks[0] === 'add') {
                    $fun .= '$' . $toks[1] . ' = ' . '$' . $toks[1] . ' + ' . $tok2 . ';' . PHP_EOL ;
                } elseif ( $toks[0] === 'mul') {
                    $fun .= '$' . $toks[1] . ' = ' . '$' . $toks[1] . ' * ' . $tok2 . ';' . PHP_EOL ;
                } elseif ( $toks[0] === 'mod') {
                    $fun .= '$' . $toks[1] . ' = ' . '$' . $toks[1] . ' % ' . $tok2 . ';' . PHP_EOL ;
                } elseif ( $toks[0] === 'eql') {
                    $fun .= '$' . $toks[1] . ' = (' . '$' . $toks[1] . ' === ' . $tok2 . ') ? 1 : 0;' . PHP_EOL ;
                } elseif ( $toks[0] === 'div') {
                    $fun .= '$' . $toks[1] . ' = ' . 'intdiv($' . $toks[1] . ', ' . $tok2 . ');' . PHP_EOL ;
                }
            }
        }
    }
    $fun .= 'return $z === 0;' . PHP_EOL . '}' . PHP_EOL;
    return $fun;
}
function day24dyn($d0, $d1, $d2, $d3, $d4, $d5, $d6, $d7, $d8, $d9, $d10, $d11, $d12, $d13)
{
    $x = 0;
    $y = 0;
    $z = 0;
    $w = $d0;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 14;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 12;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d1;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 10;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 9;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d2;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 13;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 8;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d3;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -8;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 3;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d4;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 11;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 0;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d5;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 11;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 11;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d6;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 14;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 10;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d7;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -11;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 13;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d8;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 1);
    $x = $x + 14;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 3;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d9;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -1;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 10;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d10;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -8;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 10;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d11;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -5;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 14;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d12;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -16;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 6;
    $y = $y * $x;
    $z = $z + $y;
    $w = $d13;
    $x = $x * 0;
    $x = $x + $z;
    $x = $x % 26;
    $z = intdiv($z, 26);
    $x = $x + -6;
    $x = ($x === $w) ? 1 : 0;
    $x = ($x === 0) ? 1 : 0;
    $y = $y * 0;
    $y = $y + 25;
    $y = $y * $x;
    $y = $y + 1;
    $z = $z * $y;
    $y = $y * 0;
    $y = $y + $w;
    $y = $y + 5;
    $y = $y * $x;
    $z = $z + $y;
    return $z;
}

function day24(string $filename ) {
    $strcontent = file_get_contents($filename );
    $lines = explode("\n", $strcontent);
    $day24Prog = day24Prog( $lines );

    print $day24Prog;

    print day24dyn(3,9,9,9,9,6,9, 8,7,9,9,4,2,9) . PHP_EOL;
    print day24dyn(1,8,1,1,6,1,2,1,1,3,4,1,1,7) . PHP_EOL;

}


day24( '../data/day24.txt' );
